### PR TITLE
feat(service): software engineering page

### LINKED ISSUE #146: Software Engineering page | Service page
To create a Software Engineering page that should have a path: 
Home > Services > Software Engineering

It can be accessible via: 
https://valor-software.com/services
https://valor-software.com/
main menu 

Design: https://www.figma.com/file/StpiCGh7YZyAPRjtD5gJBo/Valor-Site-Design-2021?node-id=9361%3A46168

### PR DESCRIPTION
**Pull request by andsonjosef**
closes #146

### CODE REVIEW

**Comment by Alexveselun** [comment]
On the "Sevice" page the links look not clickable:

Screenshot from 2022-09-19 14-21-42

**Comment by Alexveselun** [comment]
Links to some projects are not correct

Screenshot from 2022-09-19 14-36-24
Screenshot from 2022-09-19 14-36-43

**Comment by andsonjosef** [comment]
@Alexveselun we will have one PR for each of the cards e services, so in each of them a only enable one clicacble card, all of them will be working when we merge it.

**Comment by andsonjosef** [comment]
@Alexveselun  the links wich are not clicable is because we don't have release it yet. In meeting with Olga she said that they might be available before the release of this page, or we can take it out later.

**Comment by andsonjosef** [comment]
@Alexveselun the icon issue was fixed

**Review by sergeimelnik1980 — APPROVED** [review]

**Pull request merged**
