### PR TITLE
Terminus page

### LINKED ISSUE #94: Terminus Project Page
To implement Terminus project page.

Design: https://www.figma.com/file/StpiCGh7YZyAPRjtD5gJBo/Valor-Site-Design-2021?node-id=10114%3A6872

Content (with all images): https://docs.google.com/document/d/1Nxe27ReFea2UG8WbIYCp2rejW40tKL1oy-V0fXQMcT4/edit#

### PR DESCRIPTION
**Pull request by andsonjosef**
Closes #94 

Page route: projects/terminus

### CODE REVIEW

**Comment by Alexveselun** [comment]
Terminus page: The logo on "New cloud service for the Email Experiences module" > "Technologies" section displayed not correct
Screenshot_2022-08-10_11-51-29

**Comment by Alexveselun** [comment]
Terminus page: 
The main picture in video displayed is not as expected in the design
Screenshot_2022-08-10_12-06-34

**Comment by Alexveselun** [comment]
On the "Main" page in the "Technology" section, the Terminus project is not displayed.

**Comment by Alexveselun** [comment]
On the Terminus page, the fonts are different on the all page

**Comment by Alexveselun** [comment]
Testing complete. Before deploy issues must be fixed

**Comment by KseniaKoniayeva** [comment]
> On the Terminus page, the fonts are different on the all page

according to @andsonjosef the font is the same as the other projects and Figma. Can you pls add more details here @Alexveselun ?

**Comment by Alexveselun** [comment]
> > On the Terminus page, the fonts are different on the all page
> 
> according to @andsonjosef the font is the same as the other projects and Figma. Can you pls add more details here @Alexveselun ?

Perhaps it seems so to me. If no one has questions I think this is not a problem)

**Comment by Alexveselun** [comment]
Testing completed. No critical issues were found.

**Review by KseniaKoniayeva — APPROVED** [review]

**Pull request merged**
