### PR TITLE
fix(aoc-profile): Ashes Of Creation Project improvements

### PR DESCRIPTION
**Pull request by AlexanderSinitsa**
- #116
- returned the commit with Ashes Of Creation Project
- reduced and change the preview image on the Home page
- fixed filtering for AoC on the Home page
- fixed issue with scrolling to the top of the page
- removed the 'Dribble' and "Behance" links
- straightened out the sections and changed fonts a bit
- added a video from youtube after the "Feedback" section

### CODE REVIEW

**Comment by Alexveselun** [comment]
The "Ashes Of Creation" project was displayed on the "Project" page two times
Screenshot_2022-08-11_13-31-17
Screenshot_2022-08-11_13-31-25

**Comment by Alexveselun** [comment]
Pictures appear to be inactive. Instead of a standard cursor, there should be or grab cursor or a hyperlink cursor
Screenshot_2022-08-11_14-08-42
r

**Comment by Alexveselun** [comment]
Feedback section. Must be Feedback only about the current project. 
Screenshot_2022-08-11_14-08-20

**Comment by Alexveselun** [comment]
"Visit a case study to learn" button must redirect to [**this link**](https://valor-software.com/articles/scully-helped-us-reach-a-99-lighthouse-score-for-a-b2c-platform), now redirecting to the "project" page
Screenshot_2022-08-11_14-43-47

**Comment by andsonjosef** [comment]
@Alexveselun  all issues were fixed. Can you please check again(as soon as the deploy finish)?

**Comment by Alexveselun** [comment]
Screenshot_2022-08-18_12-44-02

**Comment by Alexveselun** [comment]
Feedback section > The card should be wider so as not to cut off the name

Screenshot_2022-08-18_12-57-08

**Comment by Alexveselun** [comment]
Testing completed. No critical issues were found. Only one [improvement](https://github.com/valor-software/valor-software.github.io/pull/135#issuecomment-1219292695)

**Comment by KseniaKoniayeva** [comment]
@andsonjosef Please **DO NOT** merge this PR until we receive approval from Zack in [this Slack thread](https://valor-software.slack.com/archives/C01QZBFAMFW/p1660820876237649)

**Review by sergeimelnik1980 — APPROVED** [review]

**Pull request merged**
