### PR TITLE
feat(home): New main page

### PR DESCRIPTION
**Pull request by andsonjosef**

### CODE REVIEW

**Comment by AlexanderSinitsa** [comment]
The last commit contains fix for [Portfolio | Feedback section](https://github.com/valor-software/valor-software.github.io/issues/128)

**Comment by Alexveselun** [comment]
Text cursor instead of a hyperlink cursor displayed on the "Feedback" section on the "Show More" button

**Comment by Alexveselun** [comment]
The link on the button is not correct "Open Source" > We love Module Federation > "See what we are doing" button

**Comment by Alexveselun** [comment]
Generally, the page works well. No blockers. No critical issues.

**Review by KseniaKoniayeva — APPROVED** [review]

**Comment by KseniaKoniayeva** [comment]
> The link on the button is not correct "Open Source" > We love Module Federation > "See what we are doing" button

the link is correct, it leads to https://valor-software-site.firebaseapp.com/articles/announcing-strategic-partnership-with-zack-jackson-the-module-federation-inventor

**Pull request merged**
