### PR TITLE
feat(portfolio): new tablesready page

### LINKED ISSUE #133: Tables Ready | Project Page
To create project page in Portfolio for Tables Ready project. 

Designs are here: https://www.figma.com/file/StpiCGh7YZyAPRjtD5gJBo/Valor-Site-Design-2021?node-id=11411%3A13643

### PR DESCRIPTION
**Pull request by andsonjosef**
closes #133

### CODE REVIEW

**Comment by Alexveselun** [comment]
The project is not displayed on the "Technology" section on the "Home" page
Screenshot from 2022-09-13 18-37-05

**Comment by Alexveselun** [comment]
Testing completed. I think, before release, the issue needs to be fixed

**Comment by andsonjosef** [comment]
> 

fixed

**Comment by Alexveselun** [comment]
Testing completed. No critical issues found.

**Review by sergeimelnik1980 — APPROVED** [review]

**Pull request merged**
